### ISSUE TITLE
To-do list organizacao

### ISSUE THREAD

**Issue by DanielCosta12** [DanielCosta12/tokens-with-graphics#1]
- [x] Achar uma API com tokens
- [x] Usar o Vite
- [x] Implementar no site
- [ ] Estudar o Charts.js para implementar os gráficos
- [ ] Implementar junto com a api de tokens
- [ ] Deixar visualmente agradável

**Comment by DanielCosta12** [comment]
https://www.coinlore.com/cryptocurrency-data-api

**Comment by DanielCosta12** [comment]
https://api.coinlore.net/api/tickers/

**Comment by DanielCosta12** [comment]
https://www.chartjs.org/
